version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:v0.1.0
    environment:
      APP_HOST: sierra6-nerd-watcher_web_1
      APP_PORT: 5005
    restart: on-failure

  web:
    image: ghcr.io/sierra6secure/nerdwatcher-ui:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - PORT=5005