version: "3.7"

services:
  web:
    image: ghcr.io/sierra6secure/nerdwatcher-ui:latest
    restart: on-failure
    stop_grace_period: 2s # Optimized for faster stops
    networks:
      - umbrel_main_network # Removed the sub-lines that were forcing the static IP
    ports:
      - "5005:5005" 
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - PORT=5005

networks:
  umbrel_main_network:
    external: true